# Generated by Django 5.2.6 on 2025-09-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_iban_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='two_factor_otp',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
